version: '3'
services:
  sonarr:
    restart: unless-stopped
    networks:
      - piracy
    ports:
      - 8989:8989
    volumes:
      - /mnt/docker/sonarr/config:/config
      - /media/NAS/TV-docker:/tv
      - /mnt/docker/sonarr/downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    image: linuxserver/sonarr:latest
  networks:
    piracy:
      driver: overlay