version: "3.4"
services:
  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
      - 8267:8267 # Internal node port
      - 8268:8268 # Example extra node port
    environment:
      - TZ=America/Los_Angeles
      - PUID=1000
      - PGID=1000
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - nodeID=MyInternalNode
    volumes:
      - /mnt/docker/tdarr/server:/app/server
      - /mnt/docker/tdarr/configs:/app/configs
      - /mnt/docker/tdarr/logs:/app/logs
      - /media/NAS/Tdarr-media-docker:/media
      - /media/NAS/Tdarr-cache-docker:/temp