version: "3.8"
services:
  tdarr-server:
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    networks:
      - nodes
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
      - 8267:8267 # Internal node port
      - 8268:8268 # Example extra node port
    environment:
      - TZ=America/Los_Angeles
      - PUID=1000
      - PGID=1000
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      #- internalNode=true
      - nodeID=Dockerserver
    volumes:
      - /mnt/docker/tdarr/server:/app/server
      - /mnt/docker/tdarr/configs:/app/configs
      - /mnt/docker/tdarr/logs:/app/logs
      - /media/NAS/Tdarr-media-docker2:/media
      - /media/NAS/Tdarr-cache-docker2:/temp
      - /media/NAS/Tdarr-output-docker2:/output

  tdarr-nodes:
    image: ghcr.io/haveagitgat/tdarr_node:latest
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles
      - PUID=1000
      - PGID=1000
      - UMASK_SET=002
      #serverIP needs to equal the service name
      - serverIP=tdarr-server
      - serverPort=8266
      #- nodeID=DockerNode
    networks:
      - nodes
    volumes:
#      - /mnt/docker/tdarr-node2/logs:/app/logs
      - /media/NAS/Tdarr-media-docker2:/media
      - /media/NAS/Tdarr-cache-docker2:/temp
    tmpfs:
      - /app/configs
      - /app/logs

#volumes:
#  tmpfsconfig:
#    driver_opts:
#      type: tmpfs
#      device: tmpfs
networks:
  nodes:
    driver: overlay
    attachable: true
