version: '3'
services:
  radarr:
    restart: unless-stopped
    networks:
      - piracy
    ports:
      - 7887:7878
    volumes:
      - /mnt/docker/radarr/config:/config
      - /media/NAS/Movies-docker:/movies
      - /mnt/docker/radarr/downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    image: linuxserver/radarr:latest
  networks:
    piracy:
      driver: overlay