version: "3.8"

networks:
    default:
        external:
            name: whatwhat

#volumes:
#  tmpfsconfig:
#    driver_opts:
#      type: tmpfs
#      device: tmpfs

services:
  tdarr-node2:
    image: ghcr.io/haveagitgat/tdarr_node:latest
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles
      - PUID=1000
      - PGID=1000
      - UMASK_SET=002
      - serverIP=tdarr2
      - serverPort=9266

    volumes:
      - /mnt/docker/tdarr-node2/logs:/app/logs
      - /media/NAS/Tdarr-media-docker2:/media
      - /media/NAS/Tdarr-cache-docker2:/temp
    tmpfs:
      - /run
      - /tmp
      
