version: "3.8"

services:
  tdarr-wui:
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    networks:
      - nodes
    ports:
      - 9265:9265 # webUI port
      - 9266:9266 # server port
      - 9267:9267 # Internal node port
      - 9268:9268 # Example extra node port
    environment:
      - TZ=America/Los_Angeles
      - PUID=1000
      - PGID=1000
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=9266
      - webUIPort=9265
      - internalNode=true
      - nodeID=DockerNode
    volumes:
      - /mnt/docker/tdarr2/server:/app/server
      - /mnt/docker/tdarr2/configs:/app/configs
      - /mnt/docker/tdarr2/logs:/app/logs
      - /media/NAS/Tdarr-media-docker2:/media
      - /media/NAS/Tdarr-cache-docker2:/temp
      - /media/NAS/Tdarr-output-docker2:/output

tdarr-node:
  image: ghcr.io/haveagitgat/tdarr_node:latest
  restart: unless-stopped
  environment:
    - TZ=America/Los_Angeles
    - PUID=1000
    - PGID=1000
    - UMASK_SET=002
    - serverIP=tdarr_network
    - serverPort=9266
  networks:
    - nodes
  volumes:
#      - /mnt/docker/tdarr-node2/logs:/app/logs
    - /media/NAS/Tdarr-media-docker2:/media
    - /media/NAS/Tdarr-cache-docker2:/temp
  tmpfs:
    - /app/configs
    - /app/logs

#volumes:
#  tmpfsconfig:
#    driver_opts:
#      type: tmpfs
#      device: tmpfs
networks:
  nodes:
    driver: overlay
    attachable: true
